# Generated by Django 5.1.1 on 2025-02-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarParts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
    ]
