# Generated by Django 5.1.1 on 2025-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0003_brand_image_alter_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='carparts.category'),
        ),
    ]
