# Generated by Django 5.1.1 on 2025-03-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
