# Generated by Django 5.1.1 on 2025-03-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
